version: '3.9'

services:
  
  tscord-dashboard:
    container_name: tscord-dashboard 
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000