version: '3'

services:
  
  tscord-dashboard:
    container_name: tscord-dashboard 
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000