version: '3.9'

services:
  
  tscord-dashboard:
    container_name: tscord-dashboard 
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    depends_on:
      - tscord-proxy
    networks:
      - tscord-dashboard

  tscord-proxy:
    container_name: tscord-proxy
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./proxy/.env
    ports:
      - 3001:3001
    networks:
      - tscord-dashboard

networks:
  tscord-dashboard: 